theoryDct = {
'...........................ox......xo...........................':19,
'...................x.......xx.....ooo...........................':45,
'...................xo......ox.....oox........x..................':18,
'..................xxo......xx.....oooo.......x..................':21,
'............o.....xxox.....xo.....oooo.......x..................':13,
'...........oox....xoxx.....oo.....oooo.......x..................':3,
'...x.o.....oox....xoxx.....oo.....oooo.......x..................':29,
'...x.o.....oox....xoox.....ooo....ooooo......x..................':10,
'...x.o....xxxx...oooox.....ooo....ooooo......x..................':25,
'...xoo....xxox...oxoox...x.ooo....ooooo......x..................':6,
'...xxxx...xxox..ooxoox...o.ooo....ooooo......x..................':26,
'.o.xxxx...oxxx..ooxoox...oxooo....ooooo......x..................':32,
'.o.xxxx...oxxx..ooxoooo..xxooo..x.ooooo......x..................':23,
'.o.xxxx...oxxx..ooxxxxxx.oxooo..xoooooo......x..................':31,
'.o.xxxx...oxxx..ooxxxxxx.oxooo.xxooooooo.....x..................':40,
'...........................ox......xx.......x...................':29,
'..................x........xoo.....xx.......x...................':26,
'..................xx......oxoo.....xx.......x...................':43,
'..................xxx.....oxxo.....xx......ox...................':10,
'..........o......xxxx.....xxxo.....xx......ox...................':34,
'..........o......xoxx....xxxxo....oxx......ox...................':21,
'..........ox.....xxxoo...xxxxo....oxx......ox...................':12,
'..x.......xoo....xxxoo...xxxxo....oxx......ox...................':33,
'..xx......xxo....xxxoo...xoxxo...ooxx......ox...................':24,
'..xx......xxo....xxxoo..oxoxxo..xxxxx......ox...................':40,
'..xxx.....xxx....xxxxo..oxoxxo..ooxxx...o..ox...................':42,
'..xxx.....xxx....xxxxo..oxoxoo..ooxox...o.oxx.......x...........':37,
'...................x.......xx.....oooo.......x..................':44,
'...................xo......ox.....ooxo......xx..................':43,
'...................xo......xx.....oxxo.....xxo.......o..........':46,
'...................xo.....oxx.....ooxx.....xoxx......o..........':42,
'...................xo.....oxx.....oxxx....oxoxx...o..o..........':52,
'...................xoo....oxo.....ooxx....oxxxx...o.xo..........':29,
'...................xoo....oxox....ooox....oxoxx...o.oo......o...':51,
'...................xoo....oxox....ooox.o..oxxxo...oxoo......o...':11,
'...........x.......xxo....oxox....oooooo..oxxoo...oxoo......o...':30,
'...........x.......xxo....oxoooo..oooxoo..oxxoo...oxoo......o...':17,
'...........x.o...x.xoo....xooooo..oxoxoo..oxxoo...oxoo......o...':12,
'....o......xoo...x.xoo....xooooo..oxoxoo..oxooo...oxoo......o...':41,
'....o......xoo...x.xoo...ooooooo..oxoxoo.xxxooo...oxoo......o...':18,
'....o......xoo...xxxoo...oxooooo..xooxoo.xxoooo...oooo.....oo...':33,
'....................o.....xxo......xo...........................':45,
'....................o.....xxo......xo.......ox..................':37,
'....................o.....xoo.....oxxx......ox..................':29,
'....................o.....xxxx....oxxx......ooo.................':51,
'....................o.....xxxx....oxxx.....oooo....x............':42,
'....................o.....xxxxo...xxxo....xoooo....x............':38,
'....................oo....xxxoo...xxxox...xoooo....x............':53,
'....................oo....xxooo...xxoox...xoooo....xox..........':23,
'...................ooo.x..xooox...xooxx...xoxoo....xox..........':60,
'...................ooo.x..xooox...xooxo...xoxooo...xxx......x...':31,
'.................o.ooo.x..ooooxx..xooxx...xoxxoo...xxx......x...':39,
'...................x.......xx.....ooxo......oo.......o..........':42,
'...................x.......xx.....oxxo....o.oo....o..o..........':33,
'...................x....o..xx....oxxxo....o.oo....o..o..........':46,
'...................x....o..xx....oxxxx....o.oooo..o..o..........':61,
'...................x....o.oxx....oooxx....o.oxoo..o..x.......x..':52,
'...................x....o.oxx....oooxx....oooooo..o.xx.......x..':38,
'...................x....o.oxx....ooooooo..oooxoo..o.xx.......x..':51,
'...................x....o.oxx....ooxoooo..oxoxoo..ooxx....o..x..':59,
'...................x.o..o.oxo....ooooooo..oxoxoo..oxxx....ox.x..':30,
'..................ox.o..o.ooo.x..ooooxoo..oxxxoo..oxxx....ox.x..':29,
'..................ox.o.oo.oooxo..oooxooo..oxoxoo..ooxx....ox.x..':20,
'...................xo......xo......xo...........................':29,
'..................ooo......oxx.....xo...........................':37,
'..................ooo......oox.....xox......o...................':21,
'..................ooox.....oooo....xoo......o...................':45,
'..................ooox.....oooo....xooo.....ox..................':43,
'..................ooooo....oooo....xooo....xxx..................':31,
#'..................ooooo....oooox...xooo....xxx.o................':23,#COMMENT OUT THIS
'..................ooooox...oooxx...xooo....xxxoo................':13,
'.............x....oooxxx...ooxxx...xoxo....xoooo....o...........':51,
'..................ox.......ox......xo...........................':26,
'..................ooo.....xxo......xo...........................':11,
'...........x......oxo.....ooo.....ooo...........................':33,
'...o.......o......ooo.....xoo....xooo...........................':42,
'...o.......o......ooo.....xoo...ooooo.....x.....................':40,
'...o.......o......ooo.....xoo...oxooo...o.x.....o...............':29,
'...o.......o......ooo.....xxox..oxoooo..o.x.....o...............':41,
'...o.......o......ooo.....xxox..oxxooo..oooo....o...............':44,
'...o.......o......ooo...o.xxox..ooxxoo..oooox...o...............':45,
'...o.......o......ooo...ooooox..oooxxx..ooooxx..o...............':21,
'...o.......o......ooooo.ooooxo..oooxox..ooooxx..o...............':12,
'...oo......oo.....ooooo.oooooo..oooxox..ooooxx..o...............':10,
'..ooo.....ooo.....oxooo.ooooxo..oooxox..ooooxx..o...............':30,
'..ooo.....ooo.....oxooo.ooooxxo.oooxox.oooooxx..o...............':13,
'..................ooooo....oooo....xxoxx...xxo.......o..........':46,
'..................ooooo....oooo....xooxx...xoxx.....oo..........':13,
'.....o.......o....ooooo....oooo....xooxx...xoox.....oo..........':60,
'.....o.......o....ooooo....oooo....xooxx...xoox.....oo......xo..':62,
'.....o.......o....ooooo....oooo....xooxx...oxox...o.ox......xxx.':42,
'.....o.......o....ooooo....oooo....xooox..xxxooo..o.ox......xxx.':55,
'.....o.......o....ooooo....oooo....oooox..xoooox..ooox.x....xxx.':58,
'.....o.......o....ooooo....oooo....oooox.oooooox..xoox.x..x.xxx.':40,
'.....o.......o....ooooo....oooo...oooooxxxxoxxxx..xoox.x..x.xxx.':59,
'.....o.......o....ooooo....oooo...oooooxxoxoxxxxo.xoxx.x..xxxxx.':25,
'.....o.......o....ooooo..x.oooo..ooooooxxooxxxxxo.xoxx.x..xxxxx.':31,
'.....o.......o...oooooo..o.oooox.oooooxxxooxxxxxo.xoxx.x..xxxxx.':23,
'.....o.......o...oooooox.o.oooxxoooooxxxoooxxxxxo.xoxx.x..xxxxx.':26,
'.....o.......o...oooooox.oxxoxxxooxooxxxoooxxxxxooooxx.x..xxxxx.':15,
'.....o.......o.x.oooooxx.oxxoxxxooxooxxxoooxxoxxooooooox..xxxxx.':63,
'.....o.......o.x.oooooxx.oxxoxxxooxoxxxxoooxxxxxooooooxx..xxxxxx':8,
'...................x.......xx......xo...........................':34,
'...................x.......xx.....oox.......x...................':20,
'...................xo......xx.....oxx......xx...................':37,
'...................xo.....xxx.....oxoo.....xx...................':18,
'..................ooo.....oox....xxxoo.....xx...................':29,
'..................ooox....ooxo...xxxoo.....xx...................':41,
'............x.....oxxx....xoxo...xoxoo...o.xx...................':25,
'............x.....oxxx..xxxxxo...ooxoo...o.xx...................':10,
'..........o.x.....ooxx..xxxxoo..xxxxoo...o.xx...................':5,
'.....o....o.o.....ooxxx.xxxxox..xxxxxo...o.xx...................':45,
'...................xo......xo.....oxox.....ooxx.....oo..........':42,
'...................xo.....ooo.....ooox....xxoxx.....oo..........':51,
'...................xo.....ooo.....ooox....xoxxx....ooo.....o....':17,
'.................x.xo.....xooo....oxoo....xoxox....ooo.....o....':38,
'.................x.xo.....xoooo...oxxox...xooox....ooo.....o....':50,
'.................x.xo....oooooo...oxxox...xxoox...xooo.....o....':18,
'.................xxxo....oxxooo..ooooox...oxoox...xooo.....o....':21,
'.................xxxxx...oxxoooo.oooooo...oxoox...xooo.....o....':24,
'.................xxxxx..xxxxoooo.ooooooo..oxooo...xooo.....o....':22,
'................oxxxxxx.xoxxoxoo.oooxooo..oxooo...xooo.....o....':8,
'........x.......xxxxxxx.xoxxoxoo.oooxooo..oxooo...oooo....oo....':47,
'........x......oxxxxxxo.xoxxoooo.oooooxo..ooxxxx..oooo....oo....':32,
'........x....o.oxxxxxoo.xxxxooooxxxxxxxo..ooxxxx..oooo....oo....':41,
'........x...oo.oxxxxooo.xxxxooooxxxxxxxo.xxxxxxx..oooo....oo....':11,
'...o....x..ooo.oxxxoxoo.xxxooxooxxxoxxxo.xxoxxxx..oooo....oo....':10,
'...................xo......oo.....oxoo....x.oo.......o..........':26,
'...................xo.....xoo.....xooo....xooo.......o..........':51,
'...................xo....oooo.....xxoo....xxoo.....x.o..........':18,
'..................xxo....oxoo....ooooo....xxoo.....x.o..........':29,
'..................xxo....oxxxx...oooxo....xooo.....xoo..........':41,
'..................xxo....oxxxx...oxoxo...xxooo.....ooo.....o....':50,
'..................xxo....oxoxx...oooxo...oxxoo..o.xooo.....o....':40,
'..................xxo....oxoxx..ooooxo..ooxxoo..o.oooo.....o....':16,
'............o...x.xoo....xooxx..ooxoxo..ooxxoo..o.oooo.....o....':10,
'..........x.o...x.xxo.o..xooxo..ooxooo..ooxooo..o.oooo.....o....':38,
'..........x.o...x.xxo.o..xooxo..ooooooooooxooo..o.oooo.....o....':30,
'..........xoo...x.ooo.o..oooxxx.ooooooooooxooo..o.oooo.....o....':46,
'.x........x.......oxx.....oxxo.....xx......ox...................':21,
'.x........x.......xooo....xxxo....xxx......ox...................':37,
'.x........xx......xxoo....xxoo....xxxo.....ox...................':42,
'.x........xx......xxoo....xxxo....xoxx....oox.x.................':33,
'.x........xx......xxxo....xxxx...oooxxx...oox.x.................':3,
'.x.o......xo......xoxo....xoxx..xxxxxxx...oox.x.................':13,
'.x.o......xo.o....xooo....xoxx..xxxxxxx...oxx.x.....x...........':30,
'.x.o......xo.o....xooo....xxxxxxxxxxxxx...oxx.x.....x...........':25,
'.x.o......xo.o...xoooo...xxxxxxxxxxxxxx...oxx.x.....x...........':51,
'.x.o......xxxo...xoxxx...xxoxxxxxxxoxxx...oox.x....ox...........':4,
'.x.oo.....xoxo...xoxxx...xxoxxxxxxxoxxx..xxxx.x....ox...........':2,
'.xxxxx....ooxx...xoxxx...xxoxxxxxxxoxxx..xxxx.x....ox...........':50,
'.xxxxx....ooxx...xoxxx...xooxxxxxxooxxx..xxxx.x...oxx.......x...':59,
'..........................xxx......xo...........................':20,
'....................o.....xxo......xx........x..................':44,
'....................o.....xxo......xxx......ox..................':34,
'....................o.....xxxx....oxxx......ox..................':46,
'....................o.....xxxx....oxxx......xoo....x............':43,
'....................o.....xxxx....xxxx....xoooo....x............':30,
'....................o.....xxxxo...xxxxx...xoooo....x............':21,
'....................oo....xxxoo...xxxox...xoxoo....x.x..........':52,
'....................oo.x..xxoox...xxoxx...xoxoo....xox..........':19,
'...................ooo.x..xooox...xooxx...xoxoo....xxx......x...':47,
'...................xo......xxo....oxxo.....xxox......o..........':38,
'...................xo......xxo....oxxxx...oooox......o..........':52,
'...................xo......xoo....oxoxx...oooxx.....oo......o...':51,
'...................xo.....oooo....oooxx...oxoxx....xoo......o...':22,
'...................xo.x...ooox....ooxxx...oooxx....ooo.....oo...':18,
'..................xxoox...oxoo....ooxox...oooox....ooo.....oo...':30,
'...........o......xooox...ooxxx...ooxox...oooox....ooo.....oo...':4,
'...ox......o......xooox...ooxxx...ooxox...oooox....ooo.....oo...':13,
'...ooo.....o.o....xooox...ooxox...ooxox...oooox....ooo.....oo...':33,
'...ooo.....o.o....xooox...ooxox..xxxxox...ooooo....ooo.o...oo...':25,
'...ooo.....o.o.o..xoooo..xxxxox..xxxxox...ooooo....ooo.o...oo...':50,
'...........................ox......xxx..........................':43,
'..................x........xx......oxx.....o....................':19,
'..................xo......xxx......oxx.....o....................':29,
'..................xo......xxxo....xxxx.....o....................':17,
'..........x......oxx......xxxo....xxxx.....o....................':20,
'..........xx.....ooxo.....xxxo....xxxx.....o....................':42,
'..........xx.....oxxo....xxxxo....oxxx....oo....................':33,
'..........xxx....oxxx....oxxxo...ooxxx....oo....................':44,
'...................x.......xx.....oox........x..................':37,
'...................x.......xx.....ooxo......xx..................':20,
'..................xxo......xx.....ooxo......xx..................':21,
'..................xxoo....xxo.....oxxo......xx..................':25,
'.................xxxoo...oxoo.....oxxo......xx..................':43,
'.................xxxoo...oxoo.....ooxo.....xxx....x.............':10,
'..........ox.....xoxoo...ooxo.....oxxo.....xxx....x.............':42,
'...x......xx.....xoxoo...ooxo.....ooxo....oxxx....x.............':12,
'...................xo......xx.....oxxo.....xxx..................':53,
'...................xo......xx.....oxxo.....xxx..................':53,
'...................xo......xx.....oxxx.....xxxx......o..........':29,
'...................xo......xxo....oxxxx....xxox......o..........':42,
'...................xo......xxo....oxxxx...oooxx......x.......x..':30,
'............x......xx......xxoo...oxxox...oooxx......x.......x..':21,
'............xx.....xxx.....xoxo...ooxxx...oooxx......x.......x..':22,
'............xx.....xxxo....xxoo...ooxxx...ooxxx.....xx.......x..':26,
'............xx.....xxxo...oooox...ooxxxx..ooxxx.....xx.......x..':31,
'...................xo.....oooo....ooxxx....xoox......o..........':52,
'...................xo.....oooo....oooxx....xoxx.....oo......o...':51,
'...................xo.....oooo....oooxx....oxxx...oooo......o...':18,
'..................xxo.....oxooo...ooxox....ooxx...oooo......o...':13,
'............ox....xoo.....oxooo...ooxox....ooxx...oooo......o...':61,
'..........o.ox....ooo.....oxooo...ooxox....ooxx...ooox......ox..':21,
'..........o.ox....ooooo...oxooo...oooxx....ooxx...ooox......ox..':23,
'.....o....o.oo....ooooox..oxoox...oooxx....ooxx...ooox......ox..':42,
'....................o.....xxxx....oxxx......xxo......x..........':43,
'....................o.....xxxx....oxxx.....oxoo.....xx..........':21,
'....................oo....xxxo....oxxxx....oxxo.....xx..........':30,
'....................oo....xxxoo...oxxxo....xxxo...x.xx..........':19,
'...................ooo....xxooo...xxxoo...xxxxo...x.xx..........':61,
'...................ooo.x..xxoox...xxxxo...xxxoo...x.xo.......o..':31,
'..........x........xoo.x..xxxooo..xxxxo...xxxoo...x.xo.......o..':59,
'..........x........xoo.x..xxxooo..xxxxo...xxxoo...x.xo.....oxo..':51,
'..................ooo.....ooxx....oxxo.....xx...................':21,
'..................oooo....ooxo....oxxx.....xx.x.................':42,
'..................oooo....oooo...xxxxx....oxx.x.................':51,
'.................xoooo....xooo...xxxxx....oox.x....o............':25,
'...........x.....xoxoo...ooxoo...xoxxx....oox.x....o............':45,
'...........x.....xxxoo...xoooo..xxoxoo....oooox....o............':12,
'...........xo....xxooo...xxxxxx.xxoxoo....oooox....o............':38,
'...........xo....xxooo...xxxxox.xxoxxxxx..oooox....o............':10,
'..........ooo....xoooo...xoxxox.xxoxxxxx..oxoox...xo............':52,
'...........x......oxo....oooo......xo...........................':29,
'...........xo.....ooo....oooox.....xo...........................':21,
'...........xo.....ooox...oooox.....xoo..........................':45,
'...........xo.....ooox...ooooo.....xooo......x..................':13,
'...........xxx....ooox...ooooo.....oooo.....ox..................':34,
'...........xxx....ooooo..ooxoo....xoooo.....ox..................':30,
'...........xxx....oooxo..ooooooo..xoooo.....ox..................':17,
'...o.......oox...xxoxoo..ooooooo..xoooo.....ox..................':23,
'...oo......ooo...xxooo...xxooooo.xxooxoo.xxoooo...oooo.....oo...':10,
'...oo.....xooo..oooooo...oxoxooo.xoooxoo.xxoooo...oooo.....oo...':24,
'..ooo.....oooo..oxoooo..xxxoxooo.xoooxoo.xxoooo...oooo.....oo...':8,
'..ooo...x.oooo..xxoooo..xxooxooo.ooooxooooooooo...oooo.....oo...':58,
'..ooo...x.oooo..xxoooo..xxooxooo.ooooxooooooxoo...oxoo...oooo...':62,
'..........x.x......xxo.x..xxxooo..xxxoo...xxooo...xooo.....oxo..':4,
'....o.....x.o......xoo.x..xxooox..xxxxxx..xxoox...xoox.....oxo..':17,
'....ox....x.x....o.xoo.x..oxooox..xoxxxx..xxoox...xoox.....oxo..':11,
'....ox....xox....o.oooxx..oooxxx..xoxxxx..xxoox...xoox.....oxo..':6,
'....ooo...xoxx...o.oxxxx..oxoxxx..xoxxxx..xxoox...xoox.....oxo..':18,
'..........ooo....xoooo...xoxxox.xxxxxxxx..oxoox...xox........x..':41,
'..........ooo....xoooo...xooxox.xxoxxxxx.oxxoox...xxx.......xx..':55,
'..........ooo....xoooo...xoooox.xxoxxoxx.oxxxxxx..xxx..o....xx..':31,
'..........ooo....xoooo.x.xooooxoxxoxxxxo.oxxxxxo..xxx..o....xx..':15,
'..........ooo..o.xoooo.o.xooooxoxxoxxxxoxxxxxxxo..xxx..o....xx..':49,
'..x.......xxo..o.xxoxo.o.xxooxxoxxxoxxxoxxxxxxxo.oxxx..o....xx..':13,
'..x.......xxoo.o.xxooo.o.xxooxxoxxxoxxxoxxxxxxxo.xxxx..ox...xx..':3,
'..xo......xooo.o.xxxxxxo.xxooxxoxxxoxxxoxxxxxxxo.xxxx..ox...xx..':1,
'..................ox....o.oox....ooxoooo..oxoxoo..oxxx.......x..':30,
'..................ox....o.oooox..ooxoxoo..oxxxoo..oxxx.......x..':20,
'..................oxx...o.ooxooo.ooxxxoo..oxxxoo..oxxx.......x..':22,
'..........o.......oox.x.o.oooxoo.ooxxooo..oxxxoo..oxxx.......x..':21,
'..........oo......oooxx.o.ooxooo.ooxxooo..oxxxoo..oxxx.......x..':23,
'..........oo...o..oooxooo.ooxoxo.ooxxxoo..oxxxoo..oxxx.......x..':12,
'.....o....ooo..o..ooxxooo.ooxoxo.ooxxxoo..oxxxoo..oxxx.......x..':4,
'..........xx.x...oxxx....oxxxo...ooxxx....oo....................':44,
'..........xx.x...oxxx....oxxxo...xooxx..x.ooo...................':32,
'..........xx.x..xxxxx....oxxxo..ooooxx..x.ooo...................':45,
'..........xx.x..xxxxx.x..oxxxx..ooooxo..x.oooo..................':48,
'..........xx.x..xxxxx.x.xxxxxx..ooooxo..o.oooo..o...............':8,
'...................x....o..xx....oooooo...o.oxoo..o..x.......x..':43,
'...................x....o..xx....ooxooo...oooooo..o.ox.......x..':29,
'...................x....o..xxxo..ooxooo...oooxoo..o.ox.......x..':60,
'...................x....o..xxxo..ooxxoo...oooxoo..ooxx......xx..':57,
'...................x....o..xxxo..ooxxoo...oxoxoo..ooxx...xo.xx..':59,
'...................x..o.o..xxoo..ooxooo...oooxoo..oxxx...xxxxx..':25,
'..................ooo......oxx.....xox.......o..................':44,
'..................ooo......oox.....xxo......xoo.................':30,
'..................oooo.....ooox....xxo......xoo.................':38,
'..................oooo.....ooox....xoxx.....ooo.....o...........':26,
'..................oooo....xxxox....xoxo.....oooo....o...........':39,
'..................oooo....xxoox....ooxxx..o.oooo....o...........':43,
'..................oooo....xxoox....xoxxx..oooooo..o.o...........':51,
'..................oooo....xxoox....xoxxx..oxxooo..ooo.......o...':22,
'..................oooox..ooooxx....xxxxx..oxxooo..ooo.......o...':61,
'..................oooox..ooooxx....xxxxx..oxxooo..oox.......ooo.':53,
'..................oooox..ooooooo...xxxxo..oxxxxo..ooxx......ooo.':23,
'...............o..oooooo.oooooxo...xxxxo..oxxxxo..ooxx......ooo.':58,
'...............o..oooooo.oooooxo...xxoxo..oxxxoo..oxxx.o..x.ooo.':41,
'...............o..oooooo.oooooxoo..xxoxo.oxxxxoo..oxxx.o..x.ooo.':40,
'.*...*...*xo*x*..*xxxx...*xxxoo..*xooxoo.x..ooo......o..........'.replace("*","."):33,
'.**.......o****..*oxoo*x.*ooxoox.*oooxox..x*ooxx...**o.x....xxx.'.replace("*","."):13,
'....*.....**x*****oxoxxo*xxxoxxx*xooooxx.ooooxxx....o***........'.replace("*","."):11,
'.ooooo...*oxxx...*ooxxxx.*ooxxxx.*oooxxx.*o*ooxx.*o**o.x....xxx.'.replace("*","."):52,
'........**.x..*..ooooo...xoooo*.x..xoo*......o..................'.replace("*","."):30,
'.**oooo..*oxxo**xxxxoooo.xxxoxoooxxoxoxoooxxoxooo*.xxo*o...oooo.'.replace("*","."):2,
'............*.....*xo***..oxxxx*..oxoxx*..oxoxx*..oxxo*..*xxoo..'.replace("*","."):57,
'........o..***..o.xxo**xoxxooox.oxxooxx.ooxxxxx.o*oooo...**oooo.'.replace("*","."):22,
'............**.****xo*o*oooooooxooxooooooxxxoxoo..xxxx.*.xxxxx..'.replace("*","."):55,
'...........***..***xo*..oooxox..oooxoxx.ooxooxxxo*ooox...*ooxx..'.replace("*","."):57,
'...........x......oooo...oooox.....xo...........................':43,
'...o.......o......oooo...oooox.....xx......x....................':12,
'...o.......ox.....oooo...oooxo.....xx.o....x....................':33,
'...o.......ox.....oxoo...oooxo...xoxx.o....x....................':24,
'...o.......ooo....oxoo..xxxxxo...xoxx.o....x....................':42,
'...o.......ooo....oxoo..xxxoxo...xoxx.o..oxx....................':10}
my_dict = {}
#REMEMBER TO CHANGE n TO 1 if YOU WANT THE WHITE MOVES TO BE SAVED
n = 0
with open('edax_2024jliu.txt', 'r') as file:
    dot_string = None
    first_number = None
    char = None
    for line in file:
        flag = True
        retFlag = False
        for word in line.split(" "):
            if ('.' in word or "*" in word) and flag:  # check if the line contains a period
                dot_string = word.replace("*",".")
                #print("'" + dot_string + "'" + ':',end="")
                flag = False
            if (word == 'x') or (word == 'o'):
                char = word

            if len(word) > 1 and word != "-1" and word[0] == "-" and word[1] in ["1",'2','3','4','5','6','7','8','9']:
                word = word[1:]
            if word.isnumeric():
                first_number = word 
                #print(first_number + ',')

                my_dict[(dot_string, char)] = first_number
                break 
             # if so, save it as the dot string



keys = list(my_dict.keys())
values = list(my_dict.values())

temp = {}

for i in range(1, len(my_dict)):
    temp[(keys[i-1][0],keys[i][1])] = values[i]

del my_dict[keys[-1]]



for key in temp:
    if n == 0 and key[1] == 'x' or n==1 and key[1] == 'o':
        if key not in theoryDct:
            theoryDct[key[0]] = int(temp[key])


for key in theoryDct:
        print("'" + key + "'" + ':',end="")
        print(f"{theoryDct[key]}" + ',')
